### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
content-type: application/json

{
"nome" : "Camila Teste",
"cpf" : "01923874656",
"telefone" : "49988234567",
"senha" : "bolinhas",
"matricula" : "12345",
"grupo" : 1
}

### Verbo PUT – atualiza
PUT http://localhost:8000/funcionario/1 HTTP/1.1
content-type: application/json

{
"nome" : "Camila editado",
"cpf" : "12345678909",
"telefone" : "49898989",
"senha" : "abc",
"matricula" : "54321",
"grupo" : 2
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/funcionario/1 HTTP/1.1