### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey

### Verbo GET – listar um
GET http://localhost:8000/produto/1 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey

### Verbo POST – adicionar
POST http://localhost:8000/produto/ HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey
content-type: application/json

{
"nome" : "Tenis Vans",
"descricao": "desc",
"foto": "01010111",
"valor_unitario" : 300
}

### Verbo PUT – atualiza
PUT http://localhost:8000/produto/1 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey
content-type: application/json

{
"nome" : "Tenis Vans Old School",
"descricao": "desc editado",
"foto": "01010111",
"valor_unitario": 350
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/produto/1 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey