### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey

### Verbo POST – adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey
content-type: application/json

{
"nome" : "Camila",
"cpf" : "01923874657",
"telefone" : "49988234567",
"senha" : "bolinhas",
"matricula" : "12345",
"grupo" : 1
}

### Verbo PUT – atualiza
PUT http://localhost:8000/funcionario/1 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey
content-type: application/json

{
"nome" : "Camila editado",
"cpf" : "12345678909",
"telefone" : "49898989",
"senha" : "abc",
"matricula" : "54321",
"grupo" : 2
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/funcionario/7 HTTP/1.1
x-token: uN1Pl4CL4g3sToken
x-key: uN1Pl4CL4g3sKey