### Verbo GET – listar todos
GET http://localhost:8000/produto/ HTTP/1.1

### Verbo GET – listar um
GET http://localhost:8000/produto/1 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/produto/ HTTP/1.1
content-type: application/json

{
"nome" : "Tenis Vans",
"valor" : 300
}

### Verbo PUT – atualiza
PUT http://localhost:8000/produto/1 HTTP/1.1
content-type: application/json

{
"nome" : "Tenis Vans Old School",
"valor": 350
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/produto/1 HTTP/1.1